### ISSUE TITLE
Meta: Remove this repo, move issues to Resources, rename Resources to Meta

### ISSUE THREAD

**Issue by msappir** [Toootim/Discussion#16]
Discussions = issues.
Since GitHub already separates between issues and code/text, there's no need for the confusing separation.
Let's merge Discussion and Resources and call the new, unified repo, Toootim/Meta!

**Comment by msappir** [comment]
I'd like to do this when I have some time. If I understand correctly, there's no programmatic way to merge repos, right?
So what I'll do is:

- [ ] Rename this repo (with all the issues, which are hardest to migrate?)
- [ ] Move all files in the other meta repos into this one
- [ ] Remove the other repos

Maybe @seefood knows a better way?

**Comment by seefood** [comment]
merging repos is easy, moving the issues/discussions/wiki/tasks between them is not, because it's not part of the repo, it's a github external feature.

I can easily push all the `Resources` into `Discussions` and then rename it to Meta, I just don't see what the point will be.

**Comment by msappir** [comment]
The division between the two repos seems artificial. A lot of the issues here are about `Resources` stuff.

**Comment by seefood** [comment]
it takes 2 minutes. Yair is the owner of the Toootim org in github, he can do it himself or give one of our users the permissions.

**Comment by msappir** [comment]
Stopped caring :P
